### ISSUE TITLE
Cannot update just one dependency

### ISSUE THREAD

**Issue by dmerejkowsky** [TankerHQ/dmenv#16]
Say you have a setup.py like this:

```
install_requires=[
   "path.py",
   "requests",
]
```

and `requests==2.19` in the `requirements.lock`.

If you want to bump just requests, you would modify the `setup.py` to have:

```
install_requires=[
  'path.py',
  'requests >= 2.20',
]
```

But since `lock` cleans the virtualenv, (since #12) if a new version of `path.py` is out, you'll end up bumping `path.py` too.

**Comment by cgestes** [comment]
another workaround commonly used in the npm world (when not using yarn upgrade-interactive) consists of upgrading everything, then keeping only the relevant change in the package.json (in some way the equivalent of requirements.lock here) and rerun yarn (the equivalent of dmenv install).

**Comment by dmerejkowsky** [comment]
I think with #55 we can just let people edit the lock by hand.
