### ISSUE TITLE
RFE: Support for access to global site-packages

### ISSUE THREAD

**Issue by khardix** [TankerHQ/dmenv#64]
From time to time, I unfortunately have to work with projects that has dependencies not available on PyPI, and only (sanely) installable by the system package manager (i.e. python bindings for system components). To this end, I usually use a virtual environment with access to global site packages. I would like to see basic support for this workflow to be added to dmenv.

The features I would like to see:
1.  Limit locking/freezing to the packages installed directly into the virtualenv. It should be sufficient to add the `--local` flag to `pip freeze`.

    This however causes the lock to be "incomplete", as the system dependencies are not recorded -- but when working with access to global site packages, any locking is basically an illusion. I would consider adding a warning comment to the top of the lock file to be sufficient.

    When not working with global access, the `--local` flag should have no effect, so it should be safe to add it unconditionally.

2.  Add/Pass a `--system-site-packages` flag to the virtual environment creation command (`lock`, `install`, …), so the environment can be created with global access.

---

Let me know if I can help with anything. I can try to prepare a PR, but I'm rather new to rust, so it may take a while.

And as a side note, thanks for this awesomely simple and practical project :wink:

**Comment by dmerejkowsky** [comment]
I think calling `--local` during `pip freeze` makes a lot of sense, whether we use --system-site-packages or not.

And adding a `--system-site-packages` to the lock and install command should be doable.

> I can try to prepare a PR, but I'm rather new to rust, so it may take a while.

Feel free to try :) Rust as a rather steep learning curve, but it's totally worth it. You can start with [the book](https://doc.rust-lang.org/book/) or [the koans](https://github.com/crazymykl/rust-koans).

> And as a side note, thanks for this awesomely simple and practical project

Thanks. And congrats on closing #57 :)

**Comment by dmerejkowsky** [comment]
The `--system-site-packages` has been added in the #66  PR. Feel free to take a look :)

**Comment by khardix** [comment]
Thanks!

**Comment by dmerejkowsky** [comment]
[dmenv 0.12.0](https://github.com/TankerHQ/dmenv/releases/tag/v0.12.0) is out and contains this new feature :)
