### ISSUE TITLE
Equivalent to yarn upgrade

### ISSUE THREAD

**Issue by cgestes** [TankerHQ/dmenv#68]
Hi,

how can we have a list of the outdated package, and how can I upgrade them?

```
yarn upgrade-interactive
```
would be killer :)

In the meantime I figured I could check outdated with:
```
dmenv run -- pip list --outdated --format=freeze .
```

**Comment by dmerejkowsky** [comment]
You can't have upgrade-interactive sadly, due to how python dependencies work.

You may have to *run* foo's setup.py to discover that one of foo deps needs updating.

You can, however, have a `dmenv show:outdated` command :)

**Comment by cgestes** [comment]
Just having the top level package updated would be enough. Am I missing something? 🤔

**Comment by dmerejkowsky** [comment]
Yeah, this needs to be documented somewhere.

**Comment by dmerejkowsky** [comment]
_Update: here you go: #74 _ I was so focused about tricky things I forgot to document the obvious :)
